### ISSUE TITLE
CartCard update quantity pb: infinite increment/decrement

### ISSUE THREAD

**Issue by GuillaumeDgr** [scottyzen/woonuxt#69]
When I add a product and try to change its quantity (more or less) in the CartCard, the quantity increments or decrements infinitely.
![Screenshot 2023-10-02 at 15 54 31](https://github.com/scottyzen/woonuxt/assets/29545767/5f36ba5e-e3d6-4127-9d57-6ec24f5d70fe)

**Comment by scottyzen** [comment]
Should also be fixed now

**Comment by GuillaumeDgr** [comment]
Hi, I have tested with last branch (staging?) on your project but still not working

**Comment by GuillaumeDgr** [comment]
Hi, sorry for late reply, the POST request to /graphql repeats indefinitely

**Comment by GuillaumeDgr** [comment]
Hi Scott, any solution found on this?

**Comment by GuillaumeDgr** [comment]
It seems writing @change="updateQuantity" i/o @input="updateQuantity" works in all browsers. To be confirmed.
